# vim:fileencoding=utf-8:foldmethod=marker

# Font settings
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 10.0

# Terminal bell
enable_audio_bell no

# Window layout
remember_window_size  no
initial_window_width  900
initial_window_height 500

# Background opacity
# ackground_opacity 0.7

# Layout splits
enabled_layouts splits

# Terminator like keybinds
map ctrl+shift+o launch --location=hsplit
map ctrl+shift+e launch --location=vsplit

# BEGIN_KITTY_THEME
# Adwaita dark
include current-theme.conf
# END_KITTY_THEME
